import {useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,Atom,Check,EyeOff,Lightbulb,RefreshCw,Search,Sparkles,X} from 'lucide-react';
import {storyElements,type StoryElement as El} from '../lib/elementStoryData';
import './ElementStoryStudio.css';
const examples=[['鹼金屬水池',['H','Li','Na','K'],'小氫氣球載著鋰電池，掉進鈉水池，撞上鉀樹！'],['鹵素泡泡劇',['F','Cl','Br','I','At','Ts'],'氟鳥飛去買可樂；不然拿溴掃把，愛上阿童木後踢走怪獸！'],['惰性氣體派對',['He','Ne','Ar','Kr','Xe'],'嘿！你看，啊！神祕客人進門，大家問他是誰？'],['金銀銅尋寶隊',['Cu','Ag','Au'],'銅人帶著銀盤，找到會發光的金牌。'],['碳族校園',['C','Si','Ge','Sn','Pb'],'碳鉛筆交給矽谷司機，鍺隊長把錫盒送到鉛球場。'],['第四週期接力',['K','Ca','Sc','Ti','V','Cr'],'鉀樹卡住鈣英雄，接力棒一路傳過鈧、鈦、釩與鉻。']] as const;
const styles={funny:['搞笑','教室突然傳出巨響，','，沒想到又'],adventure:['冒險','記憶塔的大門打開，','，接著勇闖'],campus:['校園','第一節化學課開始，','，下課前又遇見']} as const;type Style=keyof typeof styles;
export default function ElementStoryStudio(){
 const find=(s:string)=>storyElements.find(e=>e.s===s)!;const [selected,setSelected]=useState<El[]>(['H','Li','Na','K'].map(find));
 const [query,setQuery]=useState(''),[tab,setTab]=useState<'build'|'examples'|'practice'>('build'),[style,setStyle]=useState<Style>('funny'),[variant,setVariant]=useState(0),[hooks,setHooks]=useState<Record<string,number>>({}),[order,setOrder]=useState<string[]>([]),[answer,setAnswer]=useState<string|null>(null);
 const shown=storyElements.filter(e=>`${e.s}${e.name}${e.n}`.toLowerCase().includes(query.toLowerCase()));const hook=(e:El)=>e.hooks[hooks[e.s]||0];
 const story=useMemo(()=>{if(!selected.length)return '先選擇 3～6 個元素，故事會出現在這裡。';const c=styles[style];return `「${c[1]}${selected.map(hook).join(c[2])}${['，最後全班都牢牢記住！','，週期表變成一張故事地圖！','，每個位置都亮起記憶燈！'][variant%3]}」`;},[selected,style,variant,hooks]);
 const toggle=(e:El)=>setSelected(p=>p.some(x=>x.s===e.s)?p.filter(x=>x.s!==e.s):p.length<6?[...p,e]:p);const last=selected.at(-1);
 const recs=useMemo(()=>last?storyElements.filter(e=>!selected.some(x=>x.s===e.s)&&((e.group===last.group&&Math.abs(e.period-last.period)===1)||(e.period===last.period&&Math.abs(e.group-last.group)===1))).slice(0,4):[],[last,selected]);
 const relation=(e:El)=>e.group===last?.group?`同族${e.period<last.period?'上方':'下方'}`:`同週期${e.group<(last?.group||0)?'左鄰':'右鄰'}`;const start=()=>{setTab('practice');setOrder([]);setAnswer(null)};const blank=selected[Math.floor(selected.length/2)],expected=selected[order.length]?.s;const opts=blank?[blank,...storyElements.filter(e=>!selected.some(x=>x.s===e.s)).slice(0,2)]:[];const base=import.meta.env.BASE_URL;
 return <main className="story-studio"><header className="studio-nav"><button onClick={()=>location.href=base}><ArrowLeft/>返回首頁</button><div><span><Atom/></span><b>元素故事工作室</b><small>118 ELEMENT STORY LAB</small></div><button className="studio-review" onClick={()=>location.href=`${base}review`}><EyeOff/>個人複習</button></header>
 <section className="studio-hero"><div><span><Sparkles/> 118 個元素・每個 3 種記憶鉤子</span><h1>選幾個元素，<br/>把它們變成一場戲。</h1><p>系統依同族上下、同週期左右推薦下一個角色，再用諧音、字形或空間位置串成故事。</p></div><div className="studio-tabs">{([['build','建立故事'],['examples','範例故事'],['practice','互動練習']] as const).map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>x[0]==='practice'?start():setTab(x[0])}>{x[1]}</button>)}</div></section>
 {tab==='build'&&<div className="builder-layout"><aside className="element-picker"><header><div><small>STEP 01</small><h2>從 118 個元素選角色</h2></div><b>{selected.length} / 6</b></header><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋符號、名稱或原子序"/></label><div className="picker-grid">{shown.map(e=><button key={e.s} className={`${e.color} ${selected.some(x=>x.s===e.s)?'selected':''}`} onClick={()=>toggle(e)}><small>{e.n}</small><b>{e.s}</b><span>{e.name}</span>{selected.some(x=>x.s===e.s)&&<i><Check/></i>}</button>)}</div></aside>
 <section className="story-canvas"><span className="canvas-tape"/><header><small>STEP 02・你的元素鏈</small><button onClick={()=>setSelected([])}>清除全部</button></header><div className="selected-chain">{selected.length?selected.map((e,i)=><div key={e.s}><button className={e.color} onClick={()=>toggle(e)}><small>{e.n}</small><b>{e.s}</b><span>{e.name}</span><i><X/></i></button>{i<selected.length-1&&<em>→</em>}</div>):<p>從左側選擇元素</p>}</div>
 {recs.length>0&&<div className="smart-recommend"><div><Lightbulb/><b>下一個最適合接</b></div>{recs.map(e=><button key={e.s} onClick={()=>toggle(e)}><b>{e.s}</b><span>{e.name}・{relation(e)}</span><ArrowRight/></button>)}</div>}
 <div className="story-styles"><small>故事風格</small>{(Object.keys(styles) as Style[]).map(k=><button key={k} className={style===k?'active':''} onClick={()=>setStyle(k)}>{styles[k][0]}</button>)}</div>
 <div className="hook-editor">{selected.map(e=><article key={e.s}><b>{e.s} {e.name}</b><div>{e.hooks.map((h,i)=><button key={h} className={(hooks[e.s]||0)===i?'active':''} onClick={()=>setHooks({...hooks,[e.s]:i})}><small>{['諧音','字形','位置'][i]}</small>{h}</button>)}</div></article>)}</div>
 <div className="generated-story"><small>即時故事</small><blockquote>{story}</blockquote><div>{selected.map(e=><span key={e.s}><b>{e.s}</b>{hook(e)}</span>)}</div></div><footer><button onClick={()=>setVariant(v=>v+1)} disabled={selected.length<3}><RefreshCw/>換一個結尾</button><button className="primary" onClick={start} disabled={selected.length<3}>用這個故事練習 <ArrowRight/></button></footer></section></div>}
 {tab==='examples'&&<section className="example-gallery"><header><small>STORY RECIPES</small><h2>六種空間故事配方</h2><p>從同族上下、同週期左右與生活場景開始模仿。</p></header><div>{examples.map(ex=><article key={ex[0]}><span className="example-tape"/><small>空間串聯</small><h3>{ex[0]}</h3><div>{ex[1].map((id,j)=>{const e=find(id);return <span key={id}><b className={e.color}>{id}</b>{j<ex[1].length-1&&<i>→</i>}</span>})}</div><blockquote>「{ex[2]}」</blockquote><button onClick={()=>{setSelected(ex[1].map(find));setHooks({});setTab('build')}}>載入這個範例 <ArrowRight/></button></article>)}</div></section>}
 {tab==='practice'&&<section className="practice-studio"><header><div><small>ACTIVE RECALL</small><h2>把故事從腦中找回來</h2></div><button onClick={()=>setTab('build')}><ArrowLeft/>修改元素</button></header>{selected.length<3?<div className="practice-empty"><p>請先選擇至少 3 個元素。</p><button onClick={()=>setTab('build')}>回去選擇</button></div>:<div className="practice-grid"><article className="order-practice"><small>練習 01・順序重建</small><h3>依故事順序點回元素</h3><div className="order-slots">{selected.map((_,i)=><span key={i} className={order[i]?'filled':''}>{order[i]||'?'}</span>)}</div><div className="order-options">{[...selected].reverse().map(e=><button key={e.s} disabled={order.includes(e.s)} onClick={()=>e.s===expected&&setOrder([...order,e.s])} className={e.color}>{e.s}</button>)}</div>{order.length===selected.length?<p className="success"><Check/>順序完成！</p>:<p>回想故事中的下一幕。</p>}</article><article className="blank-practice"><small>練習 02・故事填空</small><h3>{story.replace(blank?hook(blank):'','＿＿＿＿')}</h3><div>{opts.map(e=><button key={e.s} onClick={()=>setAnswer(e.s)} className={answer===e.s?(e.s===blank.s?'correct':'wrong'):''}>{e.s}<small>{e.name}</small></button>)}</div>{answer&&<p className={answer===blank.s?'success':'retry'}>{answer===blank.s?<><Check/>答對！「{hook(blank)}」把故事接起來。</>:<>再想想前後兩幕，答案是 {blank.s}。</>}</p>}</article></div>}<aside className="practice-next"><Sparkles/><div><small>MEMGENIUS NEXT</small><h3>{order.length===selected.length&&answer===blank?.s?'這組已掌握，適合加入間隔複習':'先完成兩種主動回想'}</h3><p>完成後換一組範例，或建立第二條故事鏈。</p></div><button onClick={()=>setTab('examples')}>挑選另一組範例 <ArrowRight/></button></aside></section>}
 </main>}
