import {useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,Atom,Bookmark,Check,EyeOff,Lightbulb,Map,RefreshCw,Save,Search,Sparkles,Trash2,X} from 'lucide-react';
import {storyElements,type StoryElement as El} from '../lib/elementStoryData';
import {recordMistake} from '../lib/reviewData';
import './ElementStoryStudio.css';
const examples=[['鹼金屬水池',['H','Li','Na','K'],'小氫氣球載著鋰電池，掉進鈉水池，撞上鉀樹！'],['鹵素泡泡劇',['F','Cl','Br','I','At','Ts'],'氟鳥飛去買可樂；不然拿溴掃把，愛上阿童木後踢走怪獸！'],['惰性氣體派對',['He','Ne','Ar','Kr','Xe'],'嘿！你看，啊！神祕客人進門，大家問他是誰？'],['金銀銅尋寶隊',['Cu','Ag','Au'],'銅人帶著銀盤，找到會發光的金牌。'],['碳族校園',['C','Si','Ge','Sn','Pb'],'碳鉛筆交給矽谷司機，鍺隊長把錫盒送到鉛球場。'],['第四週期接力',['K','Ca','Sc','Ti','V','Cr'],'鉀樹卡住鈣英雄，接力棒一路傳過鈧、鈦、釩與鉻。']] as const;
const styles={funny:['搞笑','教室突然傳出巨響，','，沒想到又'],adventure:['冒險','記憶塔的大門打開，','，接著勇闖'],campus:['校園','第一節化學課開始，','，下課前又遇見']} as const;type Style=keyof typeof styles;
type SavedStory={id:number;title:string;text:string;ids:string[];hooks:Record<string,number>;style:Style};const STORY_KEY='memgenius.stories.v1';
export default function ElementStoryStudio(){
 const find=(s:string)=>storyElements.find(e=>e.s===s)!;const [selected,setSelected]=useState<El[]>(['H','Li','Na','K'].map(find));
 const [query,setQuery]=useState(''),[tab,setTab]=useState<'build'|'map'|'examples'|'practice'>('build'),[style,setStyle]=useState<Style>('funny'),[variant,setVariant]=useState(0),[hooks,setHooks]=useState<Record<string,number>>({}),[order,setOrder]=useState<string[]>([]),[answer,setAnswer]=useState<string|null>(null),[customStory,setCustomStory]=useState(''),[saved,setSaved]=useState<SavedStory[]>(()=>{try{return JSON.parse(localStorage.getItem(STORY_KEY)||'[]')}catch{return []}}),[savedNote,setSavedNote]=useState('');
 const shown=storyElements.filter(e=>`${e.s}${e.name}${e.n}`.toLowerCase().includes(query.toLowerCase()));const hook=(e:El)=>e.hooks[hooks[e.s]||0];
 const story=useMemo(()=>{if(!selected.length)return '先選擇 3～6 個元素，故事會出現在這裡。';const c=styles[style];return `「${c[1]}${selected.map(hook).join(c[2])}${['，最後全班都牢牢記住！','，週期表變成一張故事地圖！','，每個位置都亮起記憶燈！'][variant%3]}」`;},[selected,style,variant,hooks]);
 const toggle=(e:El)=>setSelected(p=>p.some(x=>x.s===e.s)?p.filter(x=>x.s!==e.s):p.length<6?[...p,e]:p);const last=selected.at(-1);
 const generated=story,activeStory=customStory||generated;const recs=useMemo(()=>last?storyElements.filter(e=>!selected.some(x=>x.s===e.s)&&((e.group===last.group&&Math.abs(e.period-last.period)===1)||(e.period===last.period&&Math.abs(e.group-last.group)===1))).slice(0,4):[],[last,selected]);
 const relation=(e:El)=>e.group===last?.group?`同族${e.period<last.period?'上方':'下方'}`:`同週期${e.group<(last?.group||0)?'左鄰':'右鄰'}`;const start=()=>{setTab('practice');setOrder([]);setAnswer(null)};const blank=selected[Math.floor(selected.length/2)],expected=selected[order.length]?.s;const opts=blank?[blank,...storyElements.filter(e=>!selected.some(x=>x.s===e.s)).slice(0,2)]:[];const base=import.meta.env.BASE_URL;
 const saveStory=()=>{if(selected.length<3)return;const item:SavedStory={id:Date.now(),title:selected.map(x=>x.s).join(' → '),text:activeStory,ids:selected.map(x=>x.s),hooks,style};const next=[item,...saved].slice(0,12);localStorage.setItem(STORY_KEY,JSON.stringify(next));setSaved(next);setSavedNote('已儲存在這台裝置')};const removeStory=(id:number)=>{const next=saved.filter(x=>x.id!==id);localStorage.setItem(STORY_KEY,JSON.stringify(next));setSaved(next)};const loadSaved=(s:SavedStory)=>{setSelected(s.ids.map(find));setHooks(s.hooks);setStyle(s.style);setCustomStory(s.text);setTab('build')};
 return <main className="story-studio"><header className="studio-nav"><button onClick={()=>location.href=base}><ArrowLeft/>返回首頁</button><div><span><Atom/></span><b>元素故事工作室</b><small>118 ELEMENT STORY LAB</small></div><button className="studio-review" onClick={()=>location.href=`${base}review`}><EyeOff/>個人複習</button></header>
 <section className="studio-hero"><div><span><Sparkles/> 地圖選取・自訂故事・間隔複習</span><h1>選幾個元素，<br/>把它們變成一場戲。</h1><p>從完整週期表畫出路線，改寫成自己的故事；答錯時系統會自動安排下一次複習。</p></div><div className="studio-tabs">{([['build','建立故事'],['map','週期表地圖'],['examples','範例故事'],['practice','互動練習']] as const).map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>x[0]==='practice'?start():setTab(x[0])}>{x[1]}</button>)}</div></section>
 {tab==='build'&&<div className="builder-layout"><aside className="element-picker"><header><div><small>STEP 01</small><h2>從 118 個元素選角色</h2></div><b>{selected.length} / 6</b></header><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋符號、名稱或原子序"/></label><div className="picker-grid">{shown.map(e=><button key={e.s} className={`${e.color} ${selected.some(x=>x.s===e.s)?'selected':''}`} onClick={()=>toggle(e)}><small>{e.n}</small><b>{e.s}</b><span>{e.name}</span>{selected.some(x=>x.s===e.s)&&<i><Check/></i>}</button>)}</div></aside>
 <section className="story-canvas"><span className="canvas-tape"/><header><small>STEP 02・你的元素鏈</small><button onClick={()=>setSelected([])}>清除全部</button></header><div className="selected-chain">{selected.length?selected.map((e,i)=><div key={e.s}><button className={e.color} onClick={()=>toggle(e)}><small>{e.n}</small><b>{e.s}</b><span>{e.name}</span><i><X/></i></button>{i<selected.length-1&&<em>→</em>}</div>):<p>從左側選擇元素</p>}</div>
 {recs.length>0&&<div className="smart-recommend"><div><Lightbulb/><b>下一個最適合接</b></div>{recs.map(e=><button key={e.s} onClick={()=>toggle(e)}><b>{e.s}</b><span>{e.name}・{relation(e)}</span><ArrowRight/></button>)}</div>}
 <div className="story-styles"><small>故事風格</small>{(Object.keys(styles) as Style[]).map(k=><button key={k} className={style===k?'active':''} onClick={()=>setStyle(k)}>{styles[k][0]}</button>)}</div>
 <div className="hook-editor">{selected.map(e=><article key={e.s}><b>{e.s} {e.name}</b><div>{e.hooks.map((h,i)=><button key={h} className={(hooks[e.s]||0)===i?'active':''} onClick={()=>setHooks({...hooks,[e.s]:i})}><small>{['諧音','字形','位置'][i]}</small>{h}</button>)}</div></article>)}</div>
 <div className="generated-story"><small>可編輯故事</small><textarea aria-label="自訂故事文字" value={customStory||generated} onChange={e=>setCustomStory(e.target.value)}/><div>{selected.map(e=><span key={e.s}><b>{e.s}</b>{hook(e)}</span>)}</div></div><footer><button onClick={()=>{setVariant(v=>v+1);setCustomStory('')}} disabled={selected.length<3}><RefreshCw/>重新產生</button><button onClick={saveStory} disabled={selected.length<3}><Save/>儲存故事</button><button className="primary" onClick={start} disabled={selected.length<3}>用這個故事練習 <ArrowRight/></button></footer>{savedNote&&<p className="saved-note"><Check/>{savedNote}</p>}{saved.length>0&&<div className="saved-stories"><h3><Bookmark/>我的故事庫</h3>{saved.map(s=><article key={s.id}><button onClick={()=>loadSaved(s)}><b>{s.title}</b><span>{s.text}</span></button><button aria-label="刪除故事" onClick={()=>removeStory(s.id)}><Trash2/></button></article>)}</div>}</section></div>}
 {tab==='map'&&<section className="periodic-story-map"><header><div><small>PERIODIC STORY MAP</small><h2>直接在週期表上畫故事路線</h2><p>依序點選 3～6 個元素；相鄰的上下或左右位置最容易形成穩定空間記憶。</p></div><b>{selected.map(x=>x.s).join(' → ')||'尚未選取'}</b></header><div className="map-groups">{Array.from({length:18},(_,i)=><span key={i}>{i+1}</span>)}</div><div className="periodic-grid">{storyElements.filter(e=>!((e.period===6||e.period===7)&&e.group===3&&e.s!==(e.period===6?'La':'Ac'))).map(e=><button key={e.s} style={{gridColumn:e.group,gridRow:e.period}} className={`${e.color} ${selected.some(x=>x.s===e.s)?'selected':''}`} onClick={()=>toggle(e)}><small>{e.n}</small><b>{e.s}</b><span>{e.name}</span></button>)}</div><div className="inner-series">{[['鑭系',storyElements.slice(57,71)],['錒系',storyElements.slice(89,103)]].map(([label,list])=><div key={label as string}><strong>{label as string}</strong>{(list as El[]).map(e=><button key={e.s} className={`${e.color} ${selected.some(x=>x.s===e.s)?'selected':''}`} onClick={()=>toggle(e)}><b>{e.s}</b><small>{e.name}</small></button>)}</div>)}</div><footer><button onClick={()=>setSelected([])}>清除路線</button><button className="primary" disabled={selected.length<3} onClick={()=>setTab('build')}><Map/>用這條路線建立故事 <ArrowRight/></button></footer></section>}
 {tab==='examples'&&<section className="example-gallery"><header><small>STORY RECIPES</small><h2>六種空間故事配方</h2><p>從同族上下、同週期左右與生活場景開始模仿。</p></header><div>{examples.map(ex=><article key={ex[0]}><span className="example-tape"/><small>空間串聯</small><h3>{ex[0]}</h3><div>{ex[1].map((id,j)=>{const e=find(id);return <span key={id}><b className={e.color}>{id}</b>{j<ex[1].length-1&&<i>→</i>}</span>})}</div><blockquote>「{ex[2]}」</blockquote><button onClick={()=>{setSelected(ex[1].map(find));setHooks({});setTab('build')}}>載入這個範例 <ArrowRight/></button></article>)}</div></section>}
 {tab==='practice'&&<section className="practice-studio"><header><div><small>ACTIVE RECALL</small><h2>把故事從腦中找回來</h2></div><button onClick={()=>setTab('build')}><ArrowLeft/>修改元素</button></header>{selected.length<3?<div className="practice-empty"><p>請先選擇至少 3 個元素。</p><button onClick={()=>setTab('build')}>回去選擇</button></div>:<div className="practice-grid"><article className="order-practice"><small>練習 01・順序重建</small><h3>依故事順序點回元素</h3><div className="order-slots">{selected.map((_,i)=><span key={i} className={order[i]?'filled':''}>{order[i]||'?'}</span>)}</div><div className="order-options">{[...selected].reverse().map(e=><button key={e.s} disabled={order.includes(e.s)} onClick={()=>{if(e.s===expected)setOrder([...order,e.s]);else recordMistake({id:`story-order-${expected}`,family:'元素故事順序',answer:expected,prompt:`故事中 ${order.at(-1)||'開頭'} 的下一個元素是？`,hint:activeStory})}} className={e.color}>{e.s}</button>)}</div>{order.length===selected.length?<p className="success"><Check/>順序完成！</p>:<p>答錯會自動加入個人間隔複習。</p>}</article><article className="blank-practice"><small>練習 02・故事填空</small><h3>{activeStory.replace(blank?hook(blank):'','＿＿＿＿')}</h3><div>{opts.map(e=><button key={e.s} onClick={()=>{setAnswer(e.s);if(e.s!==blank.s)recordMistake({id:`story-blank-${blank.s}`,family:'元素故事填空',answer:`${blank.s} ${blank.name}`,prompt:'被遮住的元素是什麼？',hint:`故事鉤子：${hook(blank)}`})}} className={answer===e.s?(e.s===blank.s?'correct':'wrong'):''}>{e.s}<small>{e.name}</small></button>)}</div>{answer&&<p className={answer===blank.s?'success':'retry'}>{answer===blank.s?<><Check/>答對！「{hook(blank)}」把故事接起來。</>:<>已加入錯題複習；答案是 {blank.s}。</>}</p>}</article></div>}<aside className="practice-next"><Sparkles/><div><small>MEMGENIUS NEXT</small><h3>{order.length===selected.length&&answer===blank?.s?'這組已掌握，適合稍後再複習':'完成兩種主動回想'}</h3><p>答錯元素已自動送到個人複習中心，依熟悉程度安排再次出現。</p></div><button onClick={()=>location.href=`${base}review`}>查看錯題排程 <ArrowRight/></button></aside></section>}
 </main>}
