import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Atom, Check, EyeOff, Lightbulb, RefreshCw, Search, Sparkles, X } from "lucide-react";
import "./ElementStoryStudio.css";

type El={n:number;s:string;name:string;hook:string;scene:string;color:string};
const elements:El[]=[
  {n:1,s:"H",name:"氫",hook:"小氫氣球",scene:"飄進教室",color:"mint"},{n:2,s:"He",name:"氦",hook:"嘿！氦氣球",scene:"把聲音變尖",color:"blue"},{n:3,s:"Li",name:"鋰",hook:"鋰電池用力",scene:"推著氣球",color:"gold"},{n:6,s:"C",name:"碳",hook:"碳鉛筆",scene:"畫出一座黑森林",color:"green"},{n:7,s:"N",name:"氮",hook:"蛋形氮氣",scene:"滾進森林",color:"green"},{n:8,s:"O",name:"氧",hook:"張嘴吸氧",scene:"把蛋吹上天",color:"green"},{n:9,s:"F",name:"氟",hook:"飛舞的氟鳥",scene:"衝進水池",color:"purple"},{n:10,s:"Ne",name:"氖",hook:"你打開氖燈",scene:"整間房閃亮",color:"blue"},{n:11,s:"Na",name:"鈉",hook:"拿起鈉鹽",scene:"掉進水池爆開",color:"gold"},{n:12,s:"Mg",name:"鎂",hook:"美肌鎂光燈",scene:"照亮爆炸現場",color:"yellow"},{n:17,s:"Cl",name:"氯",hook:"一杯可樂 Cl",scene:"冒出綠色泡泡",color:"purple"},{n:18,s:"Ar",name:"氬",hook:"啊！氬氣燈",scene:"安靜站在旁邊",color:"blue"},{n:19,s:"K",name:"鉀",hook:"卡住的鉀樹",scene:"接住飛來的鹽罐",color:"gold"},{n:25,s:"Mn",name:"錳",hook:"猛男 Mn",scene:"舉起大鐵鎚",color:"coral"},{n:26,s:"Fe",name:"鐵",hook:"鐵人 Fe 飛來",scene:"穿著鐵盔甲",color:"coral"},{n:27,s:"Co",name:"鈷",hook:"張口 Co",scene:"咬住鐵鎚",color:"coral"},{n:28,s:"Ni",name:"鎳",hook:"指著你 Ni",scene:"大喊快放手",color:"coral"},{n:29,s:"Cu",name:"銅",hook:"銅人 Cu 大哭",scene:"眼淚變成銅幣",color:"coral"},{n:30,s:"Zn",name:"鋅",hook:"真的 Zn",scene:"撿起所有硬幣",color:"coral"},{n:35,s:"Br",name:"溴",hook:"不然拿 Br 掃把",scene:"掃走綠色泡泡",color:"purple"},{n:36,s:"Kr",name:"氪",hook:"神祕客人 Kr",scene:"推門來參加派對",color:"blue"},{n:53,s:"I",name:"碘",hook:"愛上紫色碘",scene:"送出一顆愛心",color:"purple"},{n:54,s:"Xe",name:"氙",hook:"大家問 Xe 是誰",scene:"客人戴上面具",color:"blue"},{n:79,s:"Au",name:"金",hook:"金牌 Au 發光",scene:"照亮整個故事",color:"yellow"},
];
const examples=[
  {title:"鹼金屬水池",ids:["H","Li","Na","K"],story:"小氫氣球載著鋰電池，掉進鈉水池，撞上鉀樹！",tag:"上下族群"},
  {title:"鹵素泡泡劇",ids:["F","Cl","Br","I"],story:"氟鳥飛進可樂池；不然拿溴掃把，卻愛上紫色碘！",tag:"第 17 族"},
  {title:"過渡金屬鬧劇",ids:["Mn","Fe","Co","Ni","Cu","Zn"],story:"猛男飛過來，張口指著你，害銅人大哭：這是真的！",tag:"橫向鄰居"},
  {title:"惰性氣體派對",ids:["He","Ne","Ar","Kr","Xe"],story:"嘿！你看，啊！神祕客人進門，大家問他是誰？",tag:"第 18 族"},
];

export default function ElementStoryStudio(){
  const [selected,setSelected]=useState<El[]>(elements.slice(0,1).concat(elements.filter(e=>["Li","Na","K"].includes(e.s))));
  const [query,setQuery]=useState(""),[tab,setTab]=useState<"build"|"examples"|"practice">("build"),[variant,setVariant]=useState(0),[order,setOrder]=useState<string[]>([]),[answer,setAnswer]=useState<string|null>(null);
  const shown=elements.filter(e=>`${e.s}${e.name}${e.n}`.toLowerCase().includes(query.toLowerCase()));
  const story=useMemo(()=>{const lines=selected.map(e=>`${e.hook}${e.scene}`);if(!lines.length)return "先選擇 3～6 個元素，故事會出現在這裡。";const openings=["一早，","實驗室突然停電，","週期表公寓開派對，"];return `「${openings[variant%3]}${lines.join("，接著")}！」`;},[selected,variant]);
  const toggle=(e:El)=>setSelected(prev=>prev.some(x=>x.s===e.s)?prev.filter(x=>x.s!==e.s):prev.length<6?[...prev,e]:prev);
  const load=(ids:string[])=>{setSelected(ids.map(id=>elements.find(e=>e.s===id)!).filter(Boolean));setTab("build");setVariant(v=>v+1);setOrder([]);setAnswer(null)};
  const startPractice=()=>{setTab("practice");setOrder([]);setAnswer(null)};
  const expected=selected[order.length]?.s,blank=selected[Math.floor(selected.length/2)];
  const options=blank?[blank,...elements.filter(e=>!selected.some(x=>x.s===e.s)).slice(0,2)].sort((a,b)=>a.n%3-b.n%3):[];
  const base=import.meta.env.BASE_URL;
  return <main className="story-studio"><header className="studio-nav"><button onClick={()=>location.href=base}><ArrowLeft/>返回首頁</button><div><span><Atom/></span><b>元素故事工作室</b><small>STORY LINK LAB</small></div><button className="studio-review" onClick={()=>location.href=`${base}review`}><EyeOff/>個人複習</button></header>
  <section className="studio-hero"><div><span><Sparkles/> 地圖 ＋ 故事 ＋ 重複</span><h1>選幾個元素，<br/>把它們變成一場戲。</h1><p>從週期表挑選 3～6 個元素，利用符號諧音、位置與動作，自動串成一段容易回想的故事。</p></div><div className="studio-tabs">{[["build","建立故事"],["examples","範例故事"],["practice","互動練習"]].map(x=><button className={tab===x[0]?"active":""} onClick={()=>x[0]==="practice"?startPractice():setTab(x[0] as typeof tab)}>{x[1]}</button>)}</div></section>
  {tab==="build"&&<div className="builder-layout"><aside className="element-picker"><header><div><small>STEP 01</small><h2>選擇元素</h2></div><b>{selected.length} / 6</b></header><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋符號、名稱或原子序"/></label><div className="picker-grid">{shown.map(e=><button className={`${e.color} ${selected.some(x=>x.s===e.s)?"selected":""}`} onClick={()=>toggle(e)}><small>{e.n}</small><b>{e.s}</b><span>{e.name}</span>{selected.some(x=>x.s===e.s)&&<i><Check/></i>}</button>)}</div><footer><Lightbulb/><p>建議先選同一族的上下元素，或同一週期的左右鄰居。</p></footer></aside>
  <section className="story-canvas"><span className="canvas-tape"/><header><small>STEP 02・你的元素鏈</small><button onClick={()=>setSelected([])}>清除全部</button></header><div className="selected-chain">{selected.length?selected.map((e,i)=><div><button className={e.color} onClick={()=>toggle(e)}><small>{e.n}</small><b>{e.s}</b><span>{e.name}</span><i><X/></i></button>{i<selected.length-1&&<em>→</em>}</div>):<p>從左側選擇元素</p>}</div><div className="generated-story"><small>即時故事</small><blockquote>{story}</blockquote><div>{selected.map(e=><span><b>{e.s}</b>{e.hook}</span>)}</div></div><footer><button onClick={()=>setVariant(v=>v+1)} disabled={selected.length<3}><RefreshCw/>換一個開場</button><button className="primary" onClick={startPractice} disabled={selected.length<3}>用這個故事練習 <ArrowRight/></button></footer>{selected.length>0&&selected.length<3&&<p className="selection-warning">再選 {3-selected.length} 個元素就能開始練習。</p>}</section></div>}
  {tab==="examples"&&<section className="example-gallery"><header><small>STORY RECIPES</small><h2>先從這些故事配方開始</h2><p>每組都同時利用空間位置、符號諧音和連續動作。</p></header><div>{examples.map(ex=><article><span className="example-tape"/><small>{ex.tag}</small><h3>{ex.title}</h3><div>{ex.ids.map((id,j)=>{const e=elements.find(x=>x.s===id)!;return <span><b className={e.color}>{id}</b>{j<ex.ids.length-1&&<i>→</i>}</span>})}</div><blockquote>「{ex.story}」</blockquote><button onClick={()=>load(ex.ids)}>載入這個範例 <ArrowRight/></button></article>)}</div></section>}
  {tab==="practice"&&<section className="practice-studio"><header><div><small>ACTIVE RECALL</small><h2>不要只重看，把故事從腦中找回來</h2></div><button onClick={()=>setTab("build")}><ArrowLeft/>修改元素</button></header>{selected.length<3?<div className="practice-empty"><p>請先選擇至少 3 個元素。</p><button onClick={()=>setTab("build")}>回去選擇</button></div>:<div className="practice-grid"><article className="order-practice"><small>練習 01・順序重建</small><h3>依故事順序點回元素</h3><div className="order-slots">{selected.map((_,i)=><span className={order[i]?"filled":""}>{order[i]||"?"}</span>)}</div><div className="order-options">{[...selected].reverse().map(e=><button disabled={order.includes(e.s)} onClick={()=>e.s===expected&&setOrder([...order,e.s])} className={e.color}>{e.s}</button>)}</div>{order.length===selected.length?<p className="success"><Check/>順序完成！位置路徑已重建。</p>:<p>下一個元素：回想故事中的下一幕。</p>}</article><article className="blank-practice"><small>練習 02・故事填空</small><h3>{story.replace(blank?.hook||"", "＿＿＿＿")}</h3><div>{options.map(e=><button onClick={()=>setAnswer(e.s)} className={answer===e.s?(e.s===blank.s?"correct":"wrong"):""}>{e.s}<small>{e.name}</small></button>)}</div>{answer&&<p className={answer===blank.s?"success":"retry"}>{answer===blank.s?<><Check/>答對！「{blank.hook}」把故事接起來。</>:<>再想想前後兩幕，答案是 {blank.s}。</>}</p>}</article></div>}<aside className="practice-next"><Sparkles/><div><small>MEMGENIUS NEXT</small><h3>{order.length===selected.length&&answer===blank?.s?"你已掌握這組故事，下一步適合遮蔽符號":"先完成兩種主動回想"}</h3><p>完成後可換一組範例，或回到元素池建立自己的第二條故事鏈。</p></div><button onClick={()=>setTab("examples")}>挑選另一組範例 <ArrowRight/></button></aside></section>}
  </main>;
}
