import { useMemo,useState } from "react";
import { Link } from "wouter";
import { ArrowLeft,CheckCircle2,Clock3,Play,RotateCcw,Sparkles,Volume2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { RadarChart,PolarGrid,PolarAngleAxis,Radar,ResponsiveContainer } from "recharts";
import { CATEGORY_STYLE,ELEMENTS,type ElementItem } from "@/lib/elementData";
import { loadMemoryProfile,TALENT_OPTIONS,type TalentType } from "@/lib/memoryProfile";
import { ALL_TALENTS,awardTalentXp,getAdaptiveTalents,loadTalentProgress,talentLevel } from "@/lib/elementTalentProgress";
import { loadElementProgress,prioritizeElements } from "@/lib/elementProgress";

const GAME_META:Record<TalentType,{short:string;title:string;icon:string;desc:string;color:string}>={
 visualBuilder:{short:"圖像",title:"元素場景宮殿",icon:"🖼️",desc:"把元素安置進顏色與空間場景",color:"bg-sky-100 border-sky-300"},soundMimic:{short:"聲音",title:"節奏報號",icon:"🎧",desc:"聽原子序、符號、名稱三拍後提取",color:"bg-violet-100 border-violet-300"},textOrganizer:{short:"文字",title:"分類規則簿",icon:"📚",desc:"整理元素分類與週期座標",color:"bg-amber-100 border-amber-300"},actionContext:{short:"行動",title:"元素歸位",icon:"🎬",desc:"用動作指出週期與族",color:"bg-orange-100 border-orange-300"},socialOutput:{short:"社交",title:"教同學模式",icon:"🤝",desc:"用自己的話教會另一個人",color:"bg-emerald-100 border-emerald-300"},systemAccumulator:{short:"系統",title:"間隔複習任務",icon:"📈",desc:"優先修復今天到期的元素",color:"bg-teal-100 border-teal-300"},creativeConnector:{short:"創意",title:"荒謬元素故事",icon:"🧠",desc:"用誇張故事連結符號與名稱",color:"bg-pink-100 border-pink-300"},businessApplier:{short:"應用",title:"限時任務",icon:"💼",desc:"在倒數壓力下交付元素名片",color:"bg-rose-100 border-rose-300"}
};
function speak(text:string){if(!("speechSynthesis" in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="zh-TW";u.rate=.82;speechSynthesis.speak(u)}
function randomElement(){return ELEMENTS[Math.floor(Math.random()*36)]}

export default function ElementTalentArcade(){
 const [profile]=useState(()=>loadMemoryProfile());const recommended=getAdaptiveTalents(profile);const [progress,setProgress]=useState(()=>loadTalentProgress());const [active,setActive]=useState<TalentType|null>(null);const [element,setElement]=useState<ElementItem>(()=>randomElement());const [input,setInput]=useState("");const [choice,setChoice]=useState("");const [done,setDone]=useState(false);const [message,setMessage]=useState("");const [startedAt,setStartedAt]=useState(Date.now());
 const dueElement=useMemo(()=>prioritizeElements(ELEMENTS.slice(0,36),loadElementProgress())[0],[active]);
 const radarData=ALL_TALENTS.map((talent)=>({talent:GAME_META[talent].short,xp:Math.min(500,progress.talents[talent]?.xp||0),fullMark:500}));
 function start(talent:TalentType){setActive(talent);setElement(talent==="systemAccumulator"?dueElement:randomElement());setInput("");setChoice("");setDone(false);setMessage("");setStartedAt(Date.now())}
 function complete(success:boolean,why:string){setMessage(why);if(!success)return;setProgress(awardTalentXp(active!,recommended.includes(active!)?35:25));setDone(true)}
 function submit(){if(!active)return;const normalized=input.trim().toLowerCase();if(active==="visualBuilder")complete(choice===element.category,choice===element.category?"場景分類正確！":"再看一次元素分類色彩。");else if(active==="soundMimic")complete(normalized===element.symbol.toLowerCase()||normalized===element.nameZh,normalized===element.symbol.toLowerCase()||normalized===element.nameZh?"節奏提取成功！":"請再聽一次三拍。");else if(active==="textOrganizer")complete(choice===`${element.period}-${element.group||0}`,choice===`${element.period}-${element.group||0}`?"座標整理正確！":"週期或族需要重查。");else if(active==="actionContext")complete(choice===`${element.period}-${element.group||0}`,choice===`${element.period}-${element.group||0}`?"動作定位完成！":"手勢指到錯誤座標。");else if(active==="socialOutput")complete(input.trim().length>=24&&input.includes(element.symbol),input.trim().length>=24&&input.includes(element.symbol)?"你的教學說明夠完整！":"至少寫 24 字，並包含元素符號。");else if(active==="systemAccumulator")complete(normalized===element.nameZh||normalized===element.symbol.toLowerCase(),normalized===element.nameZh||normalized===element.symbol.toLowerCase()?"到期元素修復成功！":"這張複習卡還沒修好。");else if(active==="creativeConnector")complete(input.trim().length>=24&&(input.includes(element.symbol)||input.includes(element.nameZh)),input.trim().length>=24&&(input.includes(element.symbol)||input.includes(element.nameZh))?"荒謬連結已建立！":"至少寫 24 字並帶入名稱或符號。");else {const elapsed=(Date.now()-startedAt)/1000;complete(elapsed<=30&&(normalized===element.nameZh||normalized===element.symbol.toLowerCase()),elapsed<=30&&(normalized===element.nameZh||normalized===element.symbol.toLowerCase())?`在 ${Math.round(elapsed)} 秒內交付成功！`:"答案錯誤或超過 30 秒。")}}
 const options=[element,...ELEMENTS.filter((e)=>e.number!==element.number).slice(element.number%20,element.number%20+2)];
 return <div className="min-h-screen pb-16"><header className="sticky top-0 z-30 border-b bg-[#FAF6EE]/90 backdrop-blur"><div className="container h-16 flex items-center justify-between"><Link href="/periodic-table"><Button variant="ghost" size="sm"><ArrowLeft/> 週期表</Button></Link><div className="font-display font-extrabold">八大天賦遊戲中心</div><span className="text-sm font-bold text-primary">總 XP {ALL_TALENTS.reduce((sum,t)=>sum+(progress.talents[t]?.xp||0),0)}</span></div></header><main className="container max-w-6xl pt-7">
  <section className="grid lg:grid-cols-[1.1fr_.9fr] gap-6 mb-8"><div><p className="font-hand text-2xl text-primary">your adaptive double mission</p><h1 className="font-display font-extrabold text-3xl sm:text-4xl">用你的主、副天賦記住元素</h1><p className="text-muted-foreground mt-2">推薦任務完成可得 35 XP；其他自由關卡每次 25 XP。</p><div className="grid sm:grid-cols-2 gap-3 mt-5">{recommended.map((talent,index)=>{const meta=GAME_META[talent];return <button key={talent} onClick={()=>start(talent)} className={`paper-card p-5 text-left ${meta.color}`}><span className="text-xs font-bold">今日任務 {index+1} · +35 XP</span><span className="text-3xl block mt-2">{meta.icon}</span><b className="font-display text-xl block">{meta.title}</b><span className="text-sm">{meta.desc}</span></button>})}</div>{!profile&&<Link href="/train/mrt/profile"><Button variant="link" className="px-0 mt-2">設定主副天賦以取得專屬推薦</Button></Link>}</div><div className="paper-card p-4"><h2 className="font-display font-bold text-center">天賦成長雷達 · 最高顯示 500 XP</h2><div className="h-[280px]"><ResponsiveContainer width="100%" height="100%"><RadarChart data={radarData}><PolarGrid/><PolarAngleAxis dataKey="talent" tick={{fontSize:12}}/><Radar dataKey="xp" stroke="#0f766e" fill="#14b8a6" fillOpacity={.42}/></RadarChart></ResponsiveContainer></div></div></section>
  <section><div className="flex items-end justify-between mb-4"><div><p className="font-hand text-xl text-primary">all talent games</p><h2 className="font-display font-extrabold text-2xl">八種獨立關卡</h2></div><span className="text-sm text-muted-foreground">自由選擇 · 每次 +25 XP</span></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{ALL_TALENTS.map((talent)=>{const meta=GAME_META[talent],stat=progress.talents[talent];return <button key={talent} onClick={()=>start(talent)} className={`paper-card p-4 text-left border ${meta.color}`}><div className="flex justify-between"><span className="text-2xl">{meta.icon}</span><span className="text-xs font-bold">LV.{talentLevel(stat?.xp||0)}</span></div><b className="font-display block mt-2">{meta.title}</b><p className="text-xs text-muted-foreground mt-1">{meta.desc}</p><div className="h-1.5 rounded-full bg-white/60 mt-3 overflow-hidden"><div className="h-full bg-primary" style={{width:`${(stat?.xp||0)%100}%`}}/></div><span className="text-xs">{stat?.xp||0} XP · {stat?.completions||0} 次</span></button>})}</div></section>
  {active&&<section className="paper-card p-5 sm:p-7 mt-7 border-primary"><div className="flex justify-between gap-3"><div><p className="font-hand text-xl text-primary">active mission</p><h2 className="font-display font-extrabold text-2xl">{GAME_META[active].icon} {GAME_META[active].title}</h2></div><Button variant="ghost" size="sm" onClick={()=>setActive(null)}>關閉</Button></div><div className={`mt-5 rounded-2xl border-2 p-5 text-center ${CATEGORY_STYLE[element.category].className}`}><span className="text-sm">#{element.number} · {CATEGORY_STYLE[element.category].label}</span><strong className="font-display text-6xl block">{element.symbol}</strong><b>{element.nameZh}</b></div>
   <div className="mt-5">{active==="visualBuilder"&&<><p className="font-bold mb-3">把 {element.symbol} 放進正確的分類場景：</p><div className="grid grid-cols-2 sm:grid-cols-4 gap-2">{Object.entries(CATEGORY_STYLE).slice(0,8).map(([key,value])=><button key={key} onClick={()=>setChoice(key)} className={`rounded-lg border p-2 ${value.className} ${choice===key?"ring-2 ring-primary":""}`}>{value.label}</button>)}</div></>}{active==="soundMimic"&&<><Button variant="outline" onClick={()=>speak(`${element.number}、${element.nameZh}、${element.symbol}`)}><Volume2/> 聽三拍</Button><p className="mt-3 text-sm">聽完輸入元素名稱或符號：</p></>}{(active==="textOrganizer"||active==="actionContext")&&<><p className="font-bold mb-3">選出 {element.symbol} 的週期－族座標：</p><div className="grid grid-cols-3 gap-2">{[`${element.period}-${element.group||0}`,`${Math.max(1,element.period-1)}-${element.group||0}`,`${element.period}-${Math.max(1,(element.group||1)-1)}`].sort().map((value)=><button key={value} onClick={()=>setChoice(value)} className={`rounded-lg border p-3 ${choice===value?"bg-teal-100 ring-2 ring-primary":"bg-white"}`}>第 {value.split("-")[0]} 週期・第 {value.split("-")[1]} 族</button>)}</div></>}{active==="socialOutput"&&<p className="text-sm mb-2">假裝教同學：用至少 24 字說明 {element.nameZh}，並包含符號 {element.symbol}。</p>}{active==="systemAccumulator"&&<p className="text-sm mb-2">這是系統優先排出的複習卡。輸入名稱或符號完成修復。</p>}{active==="creativeConnector"&&<p className="text-sm mb-2">寫至少 24 字的荒謬故事，並帶入 {element.nameZh} 或 {element.symbol}。</p>}{active==="businessApplier"&&<p className="text-sm mb-2 flex items-center gap-1"><Clock3 className="w-4"/>30 秒內輸入名稱或符號，交付元素名片。</p>}{!(["visualBuilder","textOrganizer","actionContext"] as TalentType[]).includes(active)&&<textarea value={input} onChange={(e)=>setInput(e.target.value)} className="w-full min-h-24 rounded-xl border bg-white p-3" placeholder="在這裡輸入答案…"/>}<Button onClick={submit} disabled={done||((active==="visualBuilder"||active==="textOrganizer"||active==="actionContext")?!choice:!input.trim())} className="w-full mt-3"><Play/> 完成任務</Button>{message&&<div className={`mt-3 rounded-xl p-3 font-bold ${done?"bg-emerald-100 text-emerald-800":"bg-rose-100 text-rose-800"}`}>{done&&<CheckCircle2 className="inline w-5 mr-1"/>}{message}</div>}{done&&<Button variant="outline" onClick={()=>start(active)} className="w-full mt-2"><RotateCcw/> 再挑戰一次</Button>}</div>
  </section>}
 </main></div>
}
