import { useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowLeft, Check, CheckCircle2, Footprints, LockKeyhole, RotateCcw, Sparkles, Volume2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CATEGORY_STYLE, ELEMENTS, type ElementItem } from "@/lib/elementData";
import { CORE_FAMILIES, isFamilyComplete, isFamilyRecommendedUnlocked, loadElementCourseProgress, recordFamilyQuiz, type CoreFamily } from "@/lib/elementCourseProgress";
import { recordElementAnswer } from "@/lib/elementProgress";

const FAMILY_INFO: Record<CoreFamily,{title:string;group:string;emoji:string;story:string;rule:string}> = {
  alkali:{title:"鹼金屬",group:"第 1 族（不含氫）",emoji:"🔥",story:"一列越往下越活潑的火爆隊伍。",rule:"最外層 1 個電子，通常形成 +1 離子。"},
  alkaline:{title:"鹼土金屬",group:"第 2 族",emoji:"🪨",story:"藏在岩石與礦物裡的建築隊。",rule:"最外層 2 個電子，通常形成 +2 離子。"},
  halogen:{title:"鹵素",group:"第 17 族",emoji:"🧂",story:"只差一個電子就完整的鹽巴製造隊。",rule:"常形成 −1 離子，與金屬反應生成鹽。"},
  noble:{title:"惰性氣體",group:"第 18 族",emoji:"🎈",story:"外層電子已滿、最淡定的氣球隊。",rule:"化學性質通常穩定，常以單原子氣體存在。"},
};
function familyFromUrl(): CoreFamily { const value=new URLSearchParams(window.location.search).get("family") as CoreFamily|null; return value&&CORE_FAMILIES.includes(value)?value:"alkali"; }
function shuffle<T>(items:T[]){return [...items].sort(()=>Math.random()-.5)}
function speak(text:string){if(!("speechSynthesis" in window))return;speechSynthesis.cancel();const value=new SpeechSynthesisUtterance(text);value.lang="zh-TW";value.rate=.84;speechSynthesis.speak(value)}

export default function ElementFamilyCourse(){
  const [family,setFamily]=useState<CoreFamily>(familyFromUrl);
  const [courseProgress,setCourseProgress]=useState(()=>loadElementCourseProgress());
  const [selected,setSelected]=useState(0); const [question,setQuestion]=useState(0); const [answer,setAnswer]=useState<number|null>(null); const [correct,setCorrect]=useState(0); const [quizDone,setQuizDone]=useState(false);
  const elements=useMemo(()=>ELEMENTS.filter((element)=>element.category===family),[family]);
  const info=FAMILY_INFO[family]; const current=elements[Math.min(selected,elements.length-1)]; const quizElement=elements[question%elements.length];
  const options=useMemo(()=>shuffle([quizElement,...shuffle(elements.filter((element)=>element.number!==quizElement.number)).slice(0,2)]),[quizElement,elements,question]);
  const familyRecord=courseProgress.families[family]; const quizPassed=(familyRecord?.bestQuizPercent||0)>=80; const placementPassed=Boolean(familyRecord?.placementComplete);
  function switchFamily(next:CoreFamily){setFamily(next);setSelected(0);setQuestion(0);setAnswer(null);setCorrect(0);setQuizDone(false);window.history.replaceState(null,"",`${import.meta.env.BASE_URL}elements/course?family=${next}`)}
  function choose(element:ElementItem){if(answer!==null)return;setAnswer(element.number);const ok=element.number===quizElement.number;if(ok)setCorrect((value)=>value+1);recordElementAnswer(quizElement,ok)}
  function next(){if(question===4){const percent=Math.round(correct/5*100);setCourseProgress(recordFamilyQuiz(family,percent));setQuizDone(true)}else{setQuestion((value)=>value+1);setAnswer(null)}}
  function restartQuiz(){setQuestion(0);setAnswer(null);setCorrect(0);setQuizDone(false)}
  return <div className="min-h-screen pb-16"><header className="sticky top-0 z-30 border-b bg-[#FAF6EE]/90 backdrop-blur"><div className="container h-16 flex items-center justify-between"><Link href="/periodic-table"><Button variant="ghost" size="sm"><ArrowLeft/> 週期表</Button></Link><div className="font-display font-extrabold">核心四族課程</div><span className="text-sm font-bold text-primary">{CORE_FAMILIES.filter((item)=>isFamilyComplete(courseProgress,item)).length}/4</span></div></header>
    <main className="container max-w-6xl pt-7"><section className="mb-6"><p className="font-hand text-2xl text-primary">learn in families</p><h1 className="font-display font-extrabold text-3xl sm:text-4xl">先記四條直欄，再擴張整張週期表</h1><p className="text-muted-foreground mt-2">建議依序解鎖；鎖頭只代表推薦進度，你仍可自由探索任何族。</p></section>
      <section className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 mb-8">{CORE_FAMILIES.map((item,index)=>{const unlocked=isFamilyRecommendedUnlocked(courseProgress,item);const complete=isFamilyComplete(courseProgress,item);return <button key={item} onClick={()=>switchFamily(item)} className={`paper-card p-4 text-left ${family===item?"ring-2 ring-primary":""}`}><div className="flex justify-between"><span className="text-2xl">{FAMILY_INFO[item].emoji}</span>{complete?<CheckCircle2 className="text-emerald-600"/>:!unlocked?<LockKeyhole className="text-muted-foreground"/>:<span className="text-xs text-primary font-bold">推薦</span>}</div><b className="font-display block mt-2">{index+1}. {FAMILY_INFO[item].title}</b><span className="text-xs text-muted-foreground">{complete?"已通關":unlocked?"進行中":"自由探索"}</span></button>})}</section>
      <section className="paper-card p-5 sm:p-7 mb-7"><div className="grid lg:grid-cols-[1fr_auto] gap-5 items-center"><div><span className={`inline-flex rounded-full border px-3 py-1 text-sm ${CATEGORY_STYLE[family].className}`}>{info.group}</span><h2 className="font-display font-extrabold text-3xl mt-3">{info.emoji} {info.title}</h2><p className="mt-2 text-lg">{info.story}</p><p className="text-muted-foreground mt-1">規律：{info.rule}</p></div><div className="grid grid-cols-2 gap-2 text-sm"><div className={`rounded-xl p-3 ${quizPassed?"bg-emerald-100":"bg-secondary"}`}><b className="block">測驗 ≥80%</b><span>{familyRecord?.bestQuizPercent||0}% {quizPassed&&"✓"}</span></div><div className={`rounded-xl p-3 ${placementPassed?"bg-emerald-100":"bg-secondary"}`}><b className="block">拖放通過</b><span>{placementPassed?"完成 ✓":"尚未完成"}</span></div></div></div></section>
      <section className="mb-8"><div className="flex justify-between items-end mb-4"><div><p className="font-hand text-xl text-primary">step 1 · family cards</p><h2 className="font-display font-extrabold text-2xl">建立整族直欄</h2></div><Button variant="outline" size="sm" onClick={()=>speak(elements.map((element)=>element.nameZh).join("、"))}><Volume2/> 聽整族</Button></div><div className={`grid gap-3 ${elements.length===7?"grid-cols-4 lg:grid-cols-7":"grid-cols-3 lg:grid-cols-6"}`}>{elements.map((element,index)=><button key={element.number} onClick={()=>setSelected(index)} className={`rounded-xl border-2 p-3 text-left ${CATEGORY_STYLE[element.category].className} ${selected===index?"ring-4 ring-primary -translate-y-2 shadow-lg":""}`}><span className="text-xs">#{element.number}</span><strong className="font-display text-4xl block text-center">{element.symbol}</strong><b className="block text-center">{element.nameZh}</b></button>)}</div><div className="paper-card mt-4 p-4 flex flex-col sm:flex-row justify-between gap-3"><p><b>位置鉤子：</b>{current.symbol} 在第 {current.period} 週期、第 {current.group} 族；把 {current.nameZh} 接在同族上下元素之間。</p><Button variant="ghost" size="sm" onClick={()=>speak(`${current.nameZh}，${current.symbol}，原子序 ${current.number}`)}><Volume2/> 聽名片</Button></div></section>
      <section className="grid lg:grid-cols-[1fr_300px] gap-6"><div className="paper-card p-5 sm:p-7"><p className="font-hand text-xl text-primary">step 2 · 80% quiz</p><h2 className="font-display font-extrabold text-2xl">五題主動回想</h2>{!quizDone?<div className="mt-5"><p className="text-sm text-muted-foreground">QUESTION {question+1}/5 · 目前答對 {correct}</p><div className="text-center my-5"><span className="text-sm">符號 {quizElement.symbol} 是哪個元素？</span><strong className="font-display text-6xl block">{quizElement.symbol}</strong></div><div className="grid sm:grid-cols-3 gap-3">{options.map((option)=>{const chosen=answer===option.number;const right=answer!==null&&option.number===quizElement.number;return <button disabled={answer!==null} onClick={()=>choose(option)} key={option.number} className={`rounded-xl border-2 p-4 font-bold ${right?"bg-emerald-100 border-emerald-500":chosen?"bg-rose-100 border-rose-500":"bg-white"}`}>{option.nameZh} · #{option.number}{right&&<Check className="inline w-4 ml-1"/>}</button>})}</div>{answer!==null&&<Button className="w-full mt-4" onClick={next}>{question===4?"計算成績":"下一題"}</Button>}</div>:<div className="text-center py-9"><CheckCircle2 className={`w-14 h-14 mx-auto ${correct>=4?"text-emerald-600":"text-amber-500"}`}/><h3 className="font-display font-bold text-2xl mt-2">本次 {correct}/5 · {correct*20}%</h3><p className="text-muted-foreground mt-2">{correct>=4?"測驗門檻通過！接著完成拖放。":"還差一點，重新看卡片後再試一次。"}</p><Button variant="outline" onClick={restartQuiz} className="mt-4"><RotateCcw/> 再測一次</Button></div>}</div>
        <aside className="paper-card p-5"><p className="font-hand text-xl text-primary">step 3 · placement</p><h2 className="font-display font-extrabold text-2xl">整族拖放</h2><p className="text-sm text-muted-foreground mt-2">把本族所有元素送回正確週期與族；完成後自動蓋章。</p><Link href={`/train/elements/place?family=${family}`}><Button className="w-full mt-5"><Footprints/> 開始 {info.title}拖放</Button></Link>{isFamilyComplete(courseProgress,family)&&<div className="mt-4 rounded-xl bg-emerald-100 text-emerald-800 p-3 text-sm font-bold"><Sparkles className="inline w-4"/> 本族已通關，下一族建議路線已解鎖。</div>}</aside></section>
    </main></div>
}
