import { useState } from "react";
import { ArrowRight, Check, ChevronLeft } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { saveMemoryProfile, TALENT_OPTIONS, VARK_OPTIONS } from "@/lib/memoryProfile";
import { scoreTalentQuiz, TALENT_QUESTIONS } from "@/lib/talentQuiz";

export default function TalentQuizPage() {
  const [index, setIndex] = useState(0); const [answers, setAnswers] = useState<number[]>([]); const [done, setDone] = useState(false); const result = done ? scoreTalentQuiz(answers) : null;
  const choose = (answer: number) => { const next = [...answers]; next[index] = answer; setAnswers(next); if (index === TALENT_QUESTIONS.length - 1) { const scored = scoreTalentQuiz(next); saveMemoryProfile({ vark: scored.vark, primaryTalent: scored.primaryTalent, secondaryTalent: scored.secondaryTalent }); setDone(true); } else setIndex(index + 1); };
  const talentName = (id: string) => TALENT_OPTIONS.find((item) => item.id === id)?.name; const varkName = (id: string) => VARK_OPTIONS.find((item) => item.id === id)?.name;
  return <main className="container max-w-3xl py-8"><Link href="/train/mrt/profile" className="inline-flex items-center gap-1 text-sm text-muted-foreground"><ChevronLeft className="w-4 h-4" />個人設定</Link>{!done ? <><p className="font-hand text-2xl text-primary mt-7">12 questions, one memory route ✎</p><div className="h-2 bg-muted rounded-full mt-4"><div className="h-full bg-primary rounded-full" style={{ width: `${((index + 1) / 12) * 100}%` }} /></div><p className="text-sm font-bold mt-5">第 {index + 1}/12 題</p><h1 className="font-display font-extrabold text-3xl mt-2">{TALENT_QUESTIONS[index].title}</h1><div className="grid sm:grid-cols-2 gap-4 mt-7">{TALENT_QUESTIONS[index].options.map((option, optionIndex) => <button key={option.label} onClick={() => choose(optionIndex)} className="paper-card p-5 text-left font-bold hover:border-primary">{option.label}<ArrowRight className="w-4 h-4 float-right" /></button>)}</div></> : result && <div className="paper-card p-8 sm:p-12 mt-8 text-center"><Check className="w-14 h-14 mx-auto text-primary" /><h1 className="font-display font-extrabold text-3xl mt-4">你的記憶路線已生成</h1><div className="grid sm:grid-cols-3 gap-3 mt-7"><div className="sticky-note sticky-yellow-bg p-4"><small>VARK</small><strong className="block text-xl">{varkName(result.vark)}</strong></div><div className="sticky-note sticky-pink-bg p-4"><small>主天賦</small><strong className="block text-xl">{talentName(result.primaryTalent)}</strong></div><div className="sticky-note bg-emerald-100 p-4"><small>副天賦</small><strong className="block text-xl">{talentName(result.secondaryTalent)}</strong></div></div><p className="text-muted-foreground mt-6">結果已自動套用到捷運課程。</p><Link href="/train/mrt/course"><Button className="rounded-full mt-6">開始個人化課程</Button></Link></div>}</main>;
}
