create table if not exists public.rally_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '世界旅人' check (char_length(display_name) between 1 and 24),
  profile jsonb not null default '{}'::jsonb,
  story_state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.rally_runs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 24),
  season text not null default 'S01' check (char_length(season) between 1 and 12),
  map_id text not null check (map_id in ('taipei', 'paris', 'tokyo')),
  score integer not null check (score between 0 and 1000000),
  finish_ms integer not null check (finish_ms between 1000 and 3600000),
  rank integer not null check (rank between 1 and 4),
  ghost_path jsonb not null default '[]'::jsonb,
  raced_on date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists rally_runs_season_score_idx on public.rally_runs (season, score desc);
create index if not exists rally_runs_daily_ghost_idx on public.rally_runs (map_id, raced_on, finish_ms asc);

alter table public.rally_profiles enable row level security;
alter table public.rally_runs enable row level security;

create policy "players read own rally profile" on public.rally_profiles
for select to authenticated using ((select auth.uid()) = user_id);
create policy "players create own rally profile" on public.rally_profiles
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "players update own rally profile" on public.rally_profiles
for update to authenticated using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "season runs are publicly readable" on public.rally_runs
for select to anon, authenticated using (true);
create policy "players create own rally runs" on public.rally_runs
for insert to authenticated with check ((select auth.uid()) = user_id);

grant select, insert, update on public.rally_profiles to authenticated;
grant select on public.rally_runs to anon, authenticated;
grant insert on public.rally_runs to authenticated;
grant usage, select on sequence public.rally_runs_id_seq to authenticated;

alter publication supabase_realtime add table public.rally_runs;
