create table if not exists public.rally_seasons (
  id text primary key check (char_length(id) between 2 and 12),
  title text not null check (char_length(title) between 1 and 60),
  status text not null check (status in ('scheduled', 'active', 'closed')),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  daily_run_limit integer not null default 5 check (daily_run_limit between 1 and 20),
  finalized_at timestamptz,
  created_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create unique index if not exists rally_one_active_season_idx
on public.rally_seasons (status) where status = 'active';

insert into public.rally_seasons (id, title, status, starts_at, ends_at)
values ('S01', '記憶外交遠征', 'active', '2026-08-01 00:00:00+00', '2026-12-31 23:59:59+00')
on conflict (id) do nothing;

create table if not exists public.rally_guilds (
  slug text primary key check (slug ~ '^[a-z0-9-]{2,24}$'),
  name text not null check (char_length(name) between 1 and 40),
  country_code text not null check (country_code in ('TW', 'FR', 'JP', 'GLOBAL')),
  emblem text not null default '🌐',
  created_at timestamptz not null default now()
);

insert into public.rally_guilds (slug, name, country_code, emblem) values
  ('star-harbor', '星燈外交港', 'TW', '🏮'),
  ('lumiere-accord', '光橋協定會', 'FR', '🗼'),
  ('senbon-circle', '千燈通譯盟', 'JP', '⛩️'),
  ('memory-league', '世界記憶聯盟', 'GLOBAL', '🌐')
on conflict (slug) do nothing;

create table if not exists public.rally_affiliations (
  user_id uuid primary key references auth.users(id) on delete cascade,
  country_code text not null default 'TW' check (country_code in ('TW', 'FR', 'JP')),
  guild_slug text references public.rally_guilds(slug) on delete set null,
  updated_at timestamptz not null default now()
);

create index if not exists rally_affiliations_guild_idx
on public.rally_affiliations (guild_slug) where guild_slug is not null;

create table if not exists public.rally_sanctions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null check (char_length(reason) between 3 and 240),
  evidence jsonb not null default '{}'::jsonb,
  banned_until timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists rally_sanctions_active_user_idx
on public.rally_sanctions (user_id, banned_until desc)
where revoked_at is null;

create table if not exists public.rally_appeals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  sanction_id bigint references public.rally_sanctions(id) on delete set null,
  run_id bigint references public.rally_runs(id) on delete set null,
  reason text not null check (char_length(reason) between 10 and 500),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  resolution text check (resolution is null or char_length(resolution) between 3 and 500),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists rally_appeals_user_created_idx
on public.rally_appeals (user_id, created_at desc);
create index if not exists rally_appeals_sanction_idx
on public.rally_appeals (sanction_id) where sanction_id is not null;
create index if not exists rally_appeals_run_idx
on public.rally_appeals (run_id) where run_id is not null;

create table if not exists public.rally_season_results (
  season text not null references public.rally_seasons(id),
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null,
  country_code text not null,
  guild_slug text,
  best_score integer not null,
  best_finish_ms integer not null,
  races integer not null,
  global_rank integer not null,
  finalized_at timestamptz not null default now(),
  primary key (season, user_id)
);

create index if not exists rally_results_season_rank_idx
on public.rally_season_results (season, global_rank);
create index if not exists rally_results_user_idx
on public.rally_season_results (user_id);

create table if not exists public.rally_rewards (
  id bigint generated by default as identity primary key,
  season text not null references public.rally_seasons(id),
  user_id uuid not null references auth.users(id) on delete cascade,
  tier text not null check (tier in ('champion', 'elite', 'finalist', 'participant')),
  coins integer not null check (coins between 0 and 100000),
  title text not null,
  claimed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (season, user_id)
);

create index if not exists rally_rewards_user_idx
on public.rally_rewards (user_id, created_at desc);

alter table public.rally_runs
  add column if not exists country_code text not null default 'TW',
  add column if not exists guild_slug text,
  add column if not exists is_valid boolean not null default true,
  add column if not exists validation_flags jsonb not null default '[]'::jsonb;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'rally_runs_country_check') then
    alter table public.rally_runs add constraint rally_runs_country_check
    check (country_code in ('TW', 'FR', 'JP'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'rally_runs_guild_fkey') then
    alter table public.rally_runs add constraint rally_runs_guild_fkey
    foreign key (guild_slug) references public.rally_guilds(slug) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'rally_runs_season_fkey') then
    alter table public.rally_runs add constraint rally_runs_season_fkey
    foreign key (season) references public.rally_seasons(id);
  end if;
end $$;

create index if not exists rally_runs_valid_country_idx
on public.rally_runs (season, country_code, score desc) where is_valid;
create index if not exists rally_runs_valid_guild_idx
on public.rally_runs (season, guild_slug, score desc)
where is_valid and guild_slug is not null;
create index if not exists rally_runs_guild_idx
on public.rally_runs (guild_slug) where guild_slug is not null;
create index if not exists rally_runs_user_daily_idx
on public.rally_runs (user_id, raced_on, season) where is_valid;

alter table public.rally_seasons enable row level security;
alter table public.rally_guilds enable row level security;
alter table public.rally_affiliations enable row level security;
alter table public.rally_sanctions enable row level security;
alter table public.rally_appeals enable row level security;
alter table public.rally_season_results enable row level security;
alter table public.rally_rewards enable row level security;

drop policy if exists "seasons are publicly readable" on public.rally_seasons;
drop policy if exists "guilds are publicly readable" on public.rally_guilds;
drop policy if exists "players read own affiliation" on public.rally_affiliations;
drop policy if exists "players create own affiliation" on public.rally_affiliations;
drop policy if exists "players update own affiliation" on public.rally_affiliations;
drop policy if exists "players read own sanctions" on public.rally_sanctions;
drop policy if exists "players read own appeals" on public.rally_appeals;
drop policy if exists "players create own pending appeals" on public.rally_appeals;
drop policy if exists "season results are publicly readable" on public.rally_season_results;
drop policy if exists "players read own rewards" on public.rally_rewards;

create policy "seasons are publicly readable" on public.rally_seasons
for select to anon, authenticated using (true);
create policy "guilds are publicly readable" on public.rally_guilds
for select to anon, authenticated using (true);
create policy "players read own affiliation" on public.rally_affiliations
for select to authenticated using ((select auth.uid()) = user_id);
create policy "players create own affiliation" on public.rally_affiliations
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "players update own affiliation" on public.rally_affiliations
for update to authenticated using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy "players read own sanctions" on public.rally_sanctions
for select to authenticated using ((select auth.uid()) = user_id);
create policy "players read own appeals" on public.rally_appeals
for select to authenticated using ((select auth.uid()) = user_id);
create policy "players create own pending appeals" on public.rally_appeals
for insert to authenticated with check (
  (select auth.uid()) = user_id and status = 'pending' and resolved_at is null
);
create policy "season results are publicly readable" on public.rally_season_results
for select to anon, authenticated using (true);
create policy "players read own rewards" on public.rally_rewards
for select to authenticated using ((select auth.uid()) = user_id);

revoke all on public.rally_seasons, public.rally_guilds, public.rally_affiliations,
  public.rally_sanctions, public.rally_appeals, public.rally_season_results,
  public.rally_rewards from anon, authenticated;
grant select on public.rally_seasons, public.rally_guilds, public.rally_season_results
to anon, authenticated;
grant select, insert, update on public.rally_affiliations to authenticated;
grant select on public.rally_sanctions, public.rally_rewards to authenticated;
grant select, insert on public.rally_appeals to authenticated;
grant usage, select on sequence public.rally_appeals_id_seq to authenticated;

create or replace view public.rally_country_leaderboard
with (security_invoker = true) as
with best as (
  select season, user_id, country_code, max(score) best_score, min(finish_ms) best_finish_ms
  from public.rally_runs where is_valid
  group by season, user_id, country_code
)
select season, country_code, count(*)::integer racers,
  sum(best_score)::bigint total_score, min(best_finish_ms)::integer best_finish_ms
from best group by season, country_code;

create or replace view public.rally_guild_leaderboard
with (security_invoker = true) as
with best as (
  select season, user_id, guild_slug, max(score) best_score, min(finish_ms) best_finish_ms
  from public.rally_runs where is_valid and guild_slug is not null
  group by season, user_id, guild_slug
)
select b.season, b.guild_slug, g.name guild_name, g.emblem,
  count(*)::integer racers, sum(b.best_score)::bigint total_score,
  min(b.best_finish_ms)::integer best_finish_ms
from best b join public.rally_guilds g on g.slug = b.guild_slug
group by b.season, b.guild_slug, g.name, g.emblem;

grant select on public.rally_country_leaderboard, public.rally_guild_leaderboard
to anon, authenticated;

create or replace function public.set_rally_affiliation(p_country_code text, p_guild_slug text)
returns void language plpgsql security invoker set search_path = '' as $$
declare v_user uuid := (select auth.uid());
begin
  if v_user is null then raise exception 'authentication required' using errcode='28000'; end if;
  if p_country_code not in ('TW','FR','JP') then raise exception 'invalid country' using errcode='22023'; end if;
  if p_guild_slug is not null and not exists (
    select 1 from public.rally_guilds where slug = p_guild_slug
  ) then raise exception 'invalid guild' using errcode='22023'; end if;
  insert into public.rally_affiliations(user_id,country_code,guild_slug)
  values(v_user,p_country_code,p_guild_slug)
  on conflict(user_id) do update set country_code=excluded.country_code,
    guild_slug=excluded.guild_slug, updated_at=now();
end $$;

create or replace function public.claim_rally_reward(p_reward_id bigint)
returns integer language plpgsql security definer set search_path = '' as $$
declare v_user uuid := (select auth.uid()); v_coins integer;
begin
  if v_user is null then raise exception 'authentication required' using errcode='28000'; end if;
  update public.rally_rewards set claimed_at=now()
  where id=p_reward_id and user_id=v_user and claimed_at is null
  returning coins into v_coins;
  if not found then raise exception 'reward unavailable' using errcode='22023'; end if;
  insert into public.rally_profiles(user_id,display_name,profile)
  values(v_user,'世界旅人',jsonb_build_object('coins',v_coins))
  on conflict(user_id) do update set profile=jsonb_set(
    coalesce(public.rally_profiles.profile,'{}'::jsonb), '{coins}',
    to_jsonb(coalesce((public.rally_profiles.profile->>'coins')::integer,0)+v_coins), true
  ), updated_at=now();
  return v_coins;
end $$;

create or replace function public.start_rally_race(p_map_id text)
returns uuid language plpgsql security definer set search_path = '' as $$
declare
  v_user uuid := (select auth.uid()); v_ticket uuid; v_limit integer; v_starts integer;
begin
  if v_user is null then raise exception 'authentication required' using errcode='28000'; end if;
  if p_map_id not in ('taipei','paris','tokyo') then raise exception 'invalid rally map' using errcode='22023'; end if;
  if exists(select 1 from public.rally_sanctions where user_id=v_user
    and revoked_at is null and banned_until>now()) then
    raise exception 'rally access temporarily suspended' using errcode='42501';
  end if;
  select daily_run_limit into v_limit from public.rally_seasons
  where status='active' and now() between starts_at and ends_at limit 1;
  if v_limit is null then raise exception 'no active rally season' using errcode='22023'; end if;
  select count(*) into v_starts from private.rally_race_sessions
  where user_id=v_user and started_at>=current_date;
  if v_starts >= v_limit*3 then raise exception 'daily race start limit reached' using errcode='22023'; end if;
  update private.rally_race_sessions set used_at=clock_timestamp()
  where user_id=v_user and used_at is null;
  insert into private.rally_race_sessions(user_id,map_id) values(v_user,p_map_id)
  returning ticket into v_ticket;
  return v_ticket;
end $$;

create or replace function public.finish_rally_race(
  p_ticket uuid, p_display_name text, p_rank integer, p_ghost_path jsonb
) returns bigint language plpgsql security definer set search_path = '' as $$
declare
  v_user uuid := (select auth.uid()); v_owner uuid; v_map_id text;
  v_started_at timestamptz; v_used_at timestamptz; v_finish_ms integer;
  v_score integer; v_run_id bigint; v_points integer; v_point jsonb;
  v_distance numeric; v_lane numeric; v_time numeric; v_prev_distance numeric := -1;
  v_prev_time numeric := -1; v_flags jsonb := '[]'::jsonb; v_valid boolean;
  v_season text; v_limit integer; v_today integer; v_country text := 'TW';
  v_guild text; v_invalid_count integer;
begin
  if v_user is null then raise exception 'authentication required' using errcode='28000'; end if;
  select user_id,map_id,started_at,used_at into v_owner,v_map_id,v_started_at,v_used_at
  from private.rally_race_sessions where ticket=p_ticket for update;
  if not found or v_owner<>v_user then raise exception 'invalid race ticket' using errcode='42501'; end if;
  if v_used_at is not null then raise exception 'race ticket already used' using errcode='22023'; end if;
  if exists(select 1 from public.rally_sanctions where user_id=v_user
    and revoked_at is null and banned_until>now()) then
    raise exception 'rally access temporarily suspended' using errcode='42501';
  end if;
  if char_length(trim(p_display_name)) not between 1 and 24 or p_rank not between 1 and 4 then
    raise exception 'invalid race metadata' using errcode='22023';
  end if;
  if jsonb_typeof(p_ghost_path)<>'array' then raise exception 'ghost path must be an array' using errcode='22023'; end if;
  v_points:=jsonb_array_length(p_ghost_path);
  if v_points not between 2 and 5000 or pg_column_size(p_ghost_path)>262144 then
    raise exception 'invalid ghost path size' using errcode='22023';
  end if;
  for v_point in select value from jsonb_array_elements(p_ghost_path) loop
    if jsonb_typeof(v_point)<>'array' or jsonb_array_length(v_point)<>3
      or jsonb_typeof(v_point->0)<>'number' or jsonb_typeof(v_point->1)<>'number'
      or jsonb_typeof(v_point->2)<>'number' then
      raise exception 'invalid ghost path point' using errcode='22023';
    end if;
    v_distance:=(v_point->>0)::numeric; v_lane:=(v_point->>1)::numeric; v_time:=(v_point->>2)::numeric;
    if v_distance<v_prev_distance or v_time<v_prev_time then
      v_flags:=v_flags||jsonb_build_array('non_monotonic_path');
    end if;
    if v_distance<0 or v_distance>330 or v_lane<-5 or v_lane>5 or v_time<0 or v_time>3600000 then
      v_flags:=v_flags||jsonb_build_array('out_of_bounds_path');
    end if;
    v_prev_distance:=v_distance; v_prev_time:=v_time;
  end loop;
  v_finish_ms:=floor(extract(epoch from(clock_timestamp()-v_started_at))*1000);
  if v_finish_ms not between 3000 and 3600000 then raise exception 'implausible race duration' using errcode='22023'; end if;
  if v_finish_ms<15000 then v_flags:=v_flags||jsonb_build_array('abnormal_speed'); end if;
  if v_points<35 or v_prev_distance<285 then v_flags:=v_flags||jsonb_build_array('incomplete_ghost'); end if;
  if abs(v_prev_time-v_finish_ms)>30000 then v_flags:=v_flags||jsonb_build_array('telemetry_clock_mismatch'); end if;
  select id,daily_run_limit into v_season,v_limit from public.rally_seasons
  where status='active' and now() between starts_at and ends_at limit 1;
  if v_season is null then raise exception 'no active rally season' using errcode='22023'; end if;
  select count(*) into v_today from public.rally_runs
  where user_id=v_user and season=v_season and raced_on=current_date and is_valid;
  if v_today>=v_limit then raise exception 'daily ranked race limit reached' using errcode='22023'; end if;
  select country_code,guild_slug into v_country,v_guild from public.rally_affiliations where user_id=v_user;
  v_country:=coalesce(v_country,'TW'); v_valid:=jsonb_array_length(v_flags)=0;
  v_score:=case when v_valid then greatest(0,least(1000000,
    round(5000000.0/v_finish_ms)+(5-p_rank)*250+least(v_points,1000))) else 0 end;
  update private.rally_race_sessions set used_at=clock_timestamp() where ticket=p_ticket;
  insert into public.rally_runs(user_id,display_name,season,map_id,score,finish_ms,rank,
    ghost_path,country_code,guild_slug,is_valid,validation_flags)
  values(v_user,trim(p_display_name),v_season,v_map_id,v_score,v_finish_ms,p_rank,
    p_ghost_path,v_country,v_guild,v_valid,v_flags) returning id into v_run_id;
  if not v_valid then
    select count(*) into v_invalid_count from public.rally_runs
    where user_id=v_user and not is_valid and created_at>now()-interval '7 days';
    if v_invalid_count>=3 and not exists(select 1 from public.rally_sanctions
      where user_id=v_user and revoked_at is null and banned_until>now()) then
      insert into public.rally_sanctions(user_id,reason,evidence,banned_until)
      values(v_user,'七日內三次異常賽事',jsonb_build_object('run_id',v_run_id,'flags',v_flags),now()+interval '24 hours');
    end if;
  end if;
  return v_run_id;
end $$;

create or replace function public.rotate_rally_season(
  p_next_season text, p_title text, p_starts_at timestamptz, p_ends_at timestamptz
) returns integer language plpgsql security definer set search_path = '' as $$
declare v_current text; v_count integer;
begin
  select id into v_current from public.rally_seasons where status='active' for update;
  if v_current is null then raise exception 'no active season' using errcode='22023'; end if;
  with ranked as (
    select user_id,(array_agg(display_name order by score desc))[1] display_name,
      (array_agg(country_code order by score desc))[1] country_code,
      (array_agg(guild_slug order by score desc))[1] guild_slug,
      max(score) best_score,min(finish_ms) best_finish_ms,count(*)::integer races,
      row_number() over(order by max(score) desc,min(finish_ms))::integer global_rank
    from public.rally_runs where season=v_current and is_valid group by user_id
  ) insert into public.rally_season_results(season,user_id,display_name,country_code,
      guild_slug,best_score,best_finish_ms,races,global_rank)
    select v_current,user_id,display_name,country_code,guild_slug,best_score,best_finish_ms,races,global_rank from ranked
    on conflict(season,user_id) do nothing;
  insert into public.rally_rewards(season,user_id,tier,coins,title)
  select season,user_id,case when global_rank=1 then 'champion' when global_rank<=10 then 'elite'
    when global_rank<=100 then 'finalist' else 'participant' end,
    case when global_rank=1 then 3000 when global_rank<=10 then 1500 when global_rank<=100 then 600 else 150 end,
    case when global_rank=1 then '世界記憶冠軍' when global_rank<=10 then '外交菁英'
      when global_rank<=100 then '賽季決選者' else '萬國遠征者' end
  from public.rally_season_results where season=v_current
  on conflict(season,user_id) do nothing;
  get diagnostics v_count=row_count;
  update public.rally_seasons set status='closed',finalized_at=now() where id=v_current;
  insert into public.rally_seasons(id,title,status,starts_at,ends_at)
  values(p_next_season,p_title,'active',p_starts_at,p_ends_at);
  return v_count;
end $$;

revoke all on function public.set_rally_affiliation(text,text),
  public.claim_rally_reward(bigint), public.start_rally_race(text),
  public.finish_rally_race(uuid,text,integer,jsonb),
  public.rotate_rally_season(text,text,timestamptz,timestamptz) from public,anon;
grant execute on function public.set_rally_affiliation(text,text),
  public.claim_rally_reward(bigint), public.start_rally_race(text),
  public.finish_rally_race(uuid,text,integer,jsonb) to authenticated;
revoke execute on function public.rotate_rally_season(text,text,timestamptz,timestamptz) from authenticated;
grant execute on function public.rotate_rally_season(text,text,timestamptz,timestamptz) to service_role;

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime'
    and schemaname='public' and tablename='rally_seasons') then
    alter publication supabase_realtime add table public.rally_seasons;
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime'
    and schemaname='public' and tablename='rally_appeals') then
    alter publication supabase_realtime add table public.rally_appeals;
  end if;
end $$;
